# Publish a release to PyPI.
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a publish job
# within `cargo-dist`.
name: "Publish to PyPI"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
      - name: "Build wheels"
        run: uv build
      - name: Publish to PyPi
        run: uv publish